version: '3.8'

services:
  pdf-processor:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped